### ISSUE TITLE
検索機能が実装できません。。

### ISSUE THREAD

**Issue by taka392** [shinonome-inc/mobile_takahiro2_basic_flutter#15]
検索ボックスの実装にて、
初期値のFlutterは表示されますが、検索ボックスにて値を入力した際に、画面が変更されずに困ってます。

//SearchBar
onSubmitted: (String value) async {
                  articles = fetchArticle(value);
              },

//repository
Future<List<Article>> fetchArticle(String search) async {
  final response = await http.get(Uri.parse('https://qiita.com/api/v2/items?page=1&per_page=20&query=body:$search'));
  if (response.statusCode == 200) {
    final List<dynamic> jsonArray = json.decode(response.body);
    List<Article> articles = jsonArray.map((json) => Article.fromJson(json)).toList();
    return articles;
  } else {
    throw Exception('Failed to load articles');
  }
}
//Feed
class FeedPageState extends State<FeedPage> {
  late Future<List<Article>> articles;

  @override
  void initState() {
    super.initState();
    articles = fetchArticle('Flutter');
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: const PreferredSize(
          preferredSize: Size.fromHeight(kToolbarHeight),
          child: SearchBar()
        ),
        body: Center(
          child: FutureBuilder<List<Article>>(
            future: articles,
            builder: (context, snapshot) {
              if (snapshot.hasData) {
                return ArticleList(
                  key: UniqueKey(),
                  articles: snapshot.data,
                );
              } else if (snapshot.hasError) {
                return Text(
                  "データの取得中にエラーが発生しました: ${snapshot.error}",
                  style: const TextStyle(color: Colors.red),
                );
              } else {
                return const CircularProgressIndicator();
              }
            },
          ),
        ),
    );
  }
}

**Comment by taka392** [comment]
![スクリーンショット 2023-06-13 20 06 21](https://github.com/shinonome-inc/mobile_takahiro2_basic_flutter/assets/88756420/03cab21f-ad5d-41b4-866e-3c91eaa34b7b)

**Comment by KobayashiYoh** [comment]
値が入力されたにもかかわらず、更新されないということは、状態管理が上手く機能していないのかもしれませんね。

**Comment by KobayashiYoh** [comment]
余談ですが、マークダウンでソースコードを載せる方法も紹介しておきます。
https://qiita.com/Qiita/items/c686397e4a0f4f11683d

**Comment by taka392** [comment]
解決しました。↑参考になります。ありがとうございます。
