### ISSUE TITLE
Dart SDKに関するgithub上でのチェック

### ISSUE THREAD

**Issue by taka392** [shinonome-inc/mobile_takahiro2_basic_flutter#19]
![スクリーンショット 2023-06-24 22 14 08](https://github.com/shinonome-inc/mobile_takahiro2_basic_flutter/assets/88756420/7ca9aea6-a575-436a-a54f-1e6893f23985)
![スクリーンショット 2023-06-24 22 19 43](https://github.com/shinonome-inc/mobile_takahiro2_basic_flutter/assets/88756420/0dd62f55-4636-4369-bcaf-68f792079560)
<img width="667" alt="スクリーンショット 2023-06-26 10 57 07" src="https://github.com/shinonome-inc/mobile_takahiro2_basic_flutter/assets/88756420/ac59c681-1f23-43d5-82f7-7c7b55011a40">
--------------------------------------------------------------------------------------------------------
github上でのチェックでSDKバージョンが2.19.4と表示されているが、
Dart SDKは3.0.5がインストールされています。原因はわかりますが、解決策がわからないため、アドバイスいただけると幸いです。どうぞよろしくお願いします。

**Comment by taka392** [comment]
flutter doctor -v
も実行しましたが、問題は見つかりませんでした

**Comment by KobayashiYoh** [comment]
GitHub上の仮想環境で用いられているDart SDKのバージョンが`2.19.4`であるのに対し、Flutterプロジェクトが要求するDart SDKバージョンが`3.0.5`以上、`4.0.0`未満であることが原因っぽいですね。
ということは、GitHubの仮想環境のDart SDKバージョンとFlutterプロジェクトが要求するDart SDKバージョンを揃えてあげる必要がありそうですね。

**Comment by taka392** [comment]
解決しました！ありがとうございます
