### ISSUE TITLE
最終課題の最終チェック

### ISSUE THREAD

**Issue by KobayashiYoh** [shinonome-inc/mobile_takahiro2_basic_flutter#33]
## 担当者
yo, kocha

**Comment by KobayashiYoh** [comment]
不具合などについて下にメモしていきます。

**Comment by KobayashiYoh** [comment]
まず、pubspec.yamlに.envの記述を追加お願いします。
レビュワーや後続の開発者が記述するよりも実装者本人が記述した方が手間もかかりませんし、思いがけないミスも防げると思います。

**Comment by kota78** [comment]
> まず、pubspec.yamlに.envの記述を追加お願いします。 レビュワーや後続の開発者が記述するよりも実装者本人が記述した方が手間もかかりませんし、思いがけないミスも防げると思います。
中身は空白or以下のような形式で！
```
clientId=
clientSecret=
```

**Comment by KobayashiYoh** [comment]
ログインのモーダルのタイトルが"article"になっているので修正お願いします。
<img src="https://github.com/shinonome-inc/mobile_takahiro2_basic_flutter/assets/82624334/d45062dd-c4e4-47b9-ab8a-f5395f0d6db3" width="300"> <img src="https://github.com/shinonome-inc/mobile_takahiro2_basic_flutter/assets/82624334/a5793a28-f99b-4729-88c9-b83df3c46aae" width="300">

**Comment by kota78** [comment]
# SettingPage
_Incorrect use of ParentDataWidget._というエラーが出てしまっています。
ちなみにスクロールは不要です！

**Comment by KobayashiYoh** [comment]
ログインのユーザーIDやパスワードを入力しようとすると、以下のような挙動になってしまうため、ログインできないです。
ログインできるように修正お願いします。
https://github.com/shinonome-inc/mobile_takahiro2_basic_flutter/assets/82624334/8de46178-b2fc-4ab6-8e43-3739c711c025

**Comment by kota78** [comment]
「アプリ情報」のPaddingが広がりすぎている気がします。
![Simulator Screen Shot - iPhone SE (3rd generation) - 2023-08-18 at 11 27 48](https://github.com/shinonome-inc/mobile_takahiro2_basic_flutter/assets/82959924/51ff6dab-fc3b-4eec-b138-27ead3b556c3)
ListTileではなく、Padding,Text,SizedBoxなどを組み合わせてシンプルに書くと良さげです。

```setting_page.dart
const ListTile(
                title: Text('アプリ情報',
                    style: TextStyle(
                      fontSize: 12,
                      color: Colors.grey,
                    )),
              ),
```

**Comment by kota78** [comment]
# FeedaPage
https://github.com/shinonome-inc/mobile_takahiro2_basic_flutter/assets/82959924/cb67152d-b292-4984-95f6-3250c8ab1271
検索ワードの入力完了時にワードが消えてしまっているようです。

**Comment by kota78** [comment]
# BottomNavigationBar
‐ 選択/非選択に関わらず文字サイズは同じにしたいです。
<img width="153" alt="スクリーンショット 2023-08-18 11 39 19" src="https://github.com/shinonome-inc/mobile_takahiro2_basic_flutter/assets/82959924/f3b2c3e6-47d8-481e-969b-1b3d58a056a0">

**Comment by KobayashiYoh** [comment]
投稿記事のユーザーIDと投稿日といいねの間にはfigmaと同じように半角スペースを入れましょう。
<img width="288" alt="スクリーンショット 2023-08-18 11 53 59" src="https://github.com/shinonome-inc/mobile_takahiro2_basic_flutter/assets/82624334/7d0e5a44-3aab-4eaf-9d80-52acef4bb2dd">

**Comment by KobayashiYoh** [comment]
FeedPageで検索していないのに検索結果がなかった場合の画面が最初に一瞬表示されたり、SettingsPageでログインしてないのにログアウトボタンが最初に一瞬表示されたりしてしまうため、修正お願いします。

https://github.com/shinonome-inc/mobile_takahiro2_basic_flutter/assets/82624334/e6b8afe7-15b3-4fa1-b626-d078a2192c9c

https://github.com/shinonome-inc/mobile_takahiro2_basic_flutter/assets/82624334/1db8d0b2-5722-4a18-99ae-e4d92bfe080f

**Comment by taka392** [comment]
クソコードですいません。
今自分のコード見ると、バカ見づらいです。。。
なぜ、こんなに意味不なコードを書いているのか、、、、

**Comment by KobayashiYoh** [comment]
## マイページ
<img src="https://github.com/shinonome-inc/mobile_takahiro2_basic_flutter/assets/82624334/05dc84f6-4ec6-46f9-8c64-b02dd7a85ec2" width="300">

3点修正お願いします。
* ユーザーIDの先頭に`@`がついていない
* フォロー・フォロワーが表示されていない
* `Another exception was thrown: Incorrect use of ParentDataWidget.`のエラーが出ている

**Comment by KobayashiYoh** [comment]
## エラー画面
FeedPageでネットワークエラーなのに回数制限エラーが表示されていたり、MyPageで再読み込みをしてもエラー画面から遷移されなかったりするので、修正お願いします。

**Comment by KobayashiYoh** [comment]
修正お疲れ様です。
既に修正できている点に関しては、issueのコメントに🚀のスタンプを押しました。
あと少しです！

**Comment by taka392** [comment]
@を追加しました。
また、FlexTextに関するエラーを解消しました。

**Comment by taka392** [comment]
https://github.com/shinonome-inc/mobile_takahiro2_basic_flutter/assets/88756420/da489570-8dc5-4289-8d8a-f9e0e61c5680

**Comment by taka392** [comment]
https://github.com/shinonome-inc/mobile_takahiro2_basic_flutter/assets/88756420/bb2be444-92d7-46a1-aa4b-4d8b59a953d6
